---
- name: Assert that the prerequisites are defined
  tags: lux
  assert:
    that:
      - lux_pkg is defined
      - lux_rel is defined

- name: Attempting to set el5 lux_rel fact
  tags: lux
  set_fact:
    lux_ver: "0-1"
  when: lux_rel == '5'

- name: Attempting to set el6 lux_rel fact
  tags: lux
  set_fact:
    lux_ver: "6-3"
  when: lux_rel == '6'

- name: Attempting to set el7 lux_rel fact
  tags: lux
  set_fact:
    lux_ver: "7-1"
  when: lux_rel == '7'

- name: Attempting to generate temporary file
  tags: lux
  tempfile:
    prefix: 'lux.'
    state: file
    suffix: '.rpm'
  register: lux_tempfile

- name: Attempting to download package to temporary location
  tags: lux
  get_url:
    dest: "{{ lux_tempfile.path }}"
    force: yes
    url: "http://repo.iotti.biz/CentOS/{{ lux_rel }}/noarch/{{ lux_pkg }}-{{ lux_ver }}.noarch.rpm"
  register: lux_get_url
  when: lux_tempfile is success

- name: Ensure that the {{ lux_pkg }} package is installed
  tags: lux
  become: true
  yum:
    disable_plugin: "{{ lux_disable_plugin|join(',') }}"
    disablerepo: "{{ lux_disablerepo|join(',') }}"
    enable_plugin: "{{ lux_enable_plugin|join(',') }}"
    enablerepo: "{{ lux_enablerepo|join(',') }}"
    name: "{{ lux_tempfile.path }}"
    state: present
  register: lux_yum
  when: lux_get_url is success

- name: Attempting to purge temporary package from the filesystem
  tags: lux
  file:
    path: "{{ lux_tempfile.path }}"
    state: absent
  when:
    - lux_tempfile is success
    - lux_yum is success

- name: Attempting to overlay lux repository configurations
  tags: lux
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: frank.repo.j2, dst: /etc/yum.repos.d/frank.repo }
    - { src: lux.repo.j2, dst: /etc/yum.repos.d/lux.repo }
  when: lux_yum is success

- name: Ensure that the lux gpg keys are installed
  tags: lux
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-LUX
    state: present
  when: lux_yum is success

- name: Ensure that the required lux packages are installed
  tags: lux
  become: true
  yum:
    disable_plugin: "{{ lux_disable_plugin|join(',') }}"
    disablerepo: "{{ lux_disablerepo|join(',') }}"
    enable_plugin: "{{ lux_enable_plugin|join(',') }}"
    enablerepo: "{{ lux_enablerepo|join(',') }}"
    name: "{{ item }}"
    state: present
  loop: "{{ lux_packages }}"
  when:
    - lux_packages|length > 0
    - lux_yum is success
...
